name: Java Unit Tests

on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '25'  

    - name: Compile Java files
      run: javac -cp "lib\junit-4.13.2.jar;lib\hamcrest-core-1.3.jar;lib\mockito-core-4.11.0.jar;lib\byte-buddy-1.14.10.jar;lib\objenesis-3.3.jar" -d bin *.java

    - name: Run tests
      run: java -cp "lib\junit-4.13.2.jar;lib\hamcrest-core-1.3.jar;lib\mockito-core-4.11.0.jar;lib\byte-buddy-1.14.10.jar;lib\objenesis-3.3.jar;bin" org.junit.runner.JUnitCore UnitTests
